CREATE TABLE Customers (
CustomerID INT IDENTITY(1, 1) PRIMARY KEY,
FirstName VARCHAR(50) NOT NULL,
LastName VARCHAR(50) NOT NULL,
Email VARCHAR(100) NOT NULL UNIQUE,
Phone VARCHAR(20) NULL,
AddressLine1 VARCHAR(100) NULL,
AddressLine2 VARCHAR(100) NULL,
City VARCHAR(50) NULL,
CreatedAt DATETIME2 NOT NULL DEFAULT SYSDATETIME()
);

CREATE TABLE Products(
ProductID INT IDENTITY(1, 1) PRIMARY KEY,
ProductName VARCHAR(100) NOT NULL,
Category VARCHAR(50) NULL,
UnitPrice DECIMAL(10, 2) NOT NULL CHECK (UnitPrice >= 0),
IsActive BIT NOT NULL DEFAULT 1,
CreatedAt DATETIME2 NOT NULL DEFAULT SYSDATETIME()
);

CREATE TABLE Orders (
OrderID INT IDENTITY(1, 1) PRIMARY KEY,
CustomerID INT NOT NULL,
ProductID INT NOT NULL,
Quantity INT NOT NULL CHECK (Quantity > 0),
OrderDate DATETIME2 NOT NULL DEFAULT SYSDATETIME(),
OrderStatus VARCHAR(20) NOT NULL DEFAULT 'Pending',
CONSTRAINT FK_Orders_Customers
	FOREIGN KEY (CustomerID) REFERENCES Customers(CustomerID),
CONSTRAINT FK_Orders_Products
	FOREIGN KEY (ProductID) REFERENCES Products(ProductID)
);

CREATE TABLE Feedback (
FeedbackID INT IDENTITY(1, 1) PRIMARY KEY,
CustomerID INT NOT NULL, 
OrderID INT NULL,
ProductID INT NULL,
Rating INT NOT NULL CHECK (Rating BETWEEN 1 AND 5),
Comment VARCHAR(500) NULL,
CreatedAt DATETIME2 NULL DEFAULT SYSDATETIME(),
CONSTRAINT FK_Feedback_Customers
	FOREIGN KEY (CustomerID) REFERENCES Customers(CustomerID),
CONSTRAINT FK_Feedback_Orders
	FOREIGN KEY (OrderID) REFERENCES Orders(OrderID),
CONSTRAINT FK_Feedback_Products
	FOREIGN KEY (ProductID) REFERENCES Products(ProductID)
);
